name: Build and Test

on: 
  pull_request:
  push:
    branches:
      - master

env:
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    runs-on: windows-latest
    strategy: 
      matrix: 
        rust: [1.40.0, stable]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        profile: minimal
        override: true
        components: rustfmt

    - name: check
      run: cargo check --all 

    - name: tests
      run: cargo test --all 

    - name: fmt
      run: cargo fmt --all -- --check
      if: matrix.rust == 'stable'
