name: Build and Test

on: 
  pull_request:
  push:
    branches:
      - master

env:
  RUSTFLAGS: -Dwarnings

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: check
      run: cargo check --all 

    - name: tests
      run: cargo test --all 

    - name: fmt
      run: cargo fmt --all -- --check
